# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sync NFTs

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync nfts
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn
      - run: yarn sync-nfts
        env:
          PROVIDER_URL: ${{ secrets.PROVIDER_URL }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Sync nfts
